#### general settings
name: BPN
train_type: bnn
eval_type: bn
gpu_ids: [2]


#### datasets
dataset:
  name: "CIFAR10"
  image_size: 32
  train_path: None

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/BLeNet_CIFAR10/"
  save_checkpoint_freq: 5


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.005  # Learning rate
  weight_decay: 0.001

#### training settings: learning rate scheme, loss, optimizer
train:
  model_name: "BLeNet"

  num_epochs: 1000
  batch_size: 128
  train_size: 1

  beta: 0.001
  prior_mu: 0
  prior_sigma: 0.01
  posterior_mu_initial: [0, 0.01]
  posterior_rho_initial: [-2, 0.01]

  in_channels: 3
  out_channels: 10

  loss: "ELBO"
