#### general settings
name: BPN
train_type: bnn-linreg
eval_type: bn
gpu_ids: [2]


#### datasets
data:
  name: "simulated"
  n: 10000
  scenario: 3

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/Simulations/BMLP_L3_S3/"
  save_checkpoint_freq: 5


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.005  # Learning rate
  weight_decay: 0.001

#### training settings: learning rate scheme, loss, optimizer
train:
  model_name: "BMLP"

  num_epochs: 100
  batch_size: 1024
  train_size: 1
  n_blocks: 3

  beta: 0.001
  prior_mu: 0
  prior_sigma: 0.01
  posterior_mu_initial: [0, 0.01]
  posterior_rho_initial: [-3, 0.01]

  in_channels: 4
  out_channels: 1

  loss: "ELBO"
