#### general settings
name: Gaussian
train_type: bnn
eval_type: bn
gpu_ids: [2]


#### datasets
data:
  name: "CIFAR10"
  image_size: 32
  train_path: None

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/BResNet_CIFAR10/"
  save_checkpoint_freq: 5


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.005  # Learning rate
  weight_decay: 0.001

model:
  name: "ResNet"
  layer_type: "gaussian"

  priors:
    prior_mu: 0
    prior_sigma: 0.01
    posterior_mu_initial: [0, 0.01]
    posterior_rho_initial: [-3, 0.01]

  in_channels: 3
  out_channels: 10

#### training settings: learning rate scheme, loss, optimizer
train:

  num_epochs: 1000
  batch_size: 256
  train_size: 1

  beta: 0.001

  loss: "ELBO"

logging:
  mode: online # disabled
  tags: [
      "CIFAR10",
      "Classification",
      "ResNet",
      "Gaussian",
    ]