#### general settings
name: BPN
train_type: cnn-mc
eval_type: cnn-mc
gpu_ids: [2]


#### datasets
data:
  name: "CIFAR100"
  image_size: 32
  train_path: None

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/LeNet_MCDropout_CIFAR100/"
  save_checkpoint_freq: 2


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.005  # Learning rate
  weight_decay: 0.001

#### training settings: learning rate scheme, loss, optimizer
train:
  model_name: "LeNet"

  num_epochs: 1000
  batch_size: 128
  train_size: 1

  in_channels: 3
  out_channels: 100

  loss: "CE"
