#### general settings
name: BPN
train_type: cnn
eval_type: cnn
gpu_ids: [2]


#### datasets
data:
  name: "ImageNet"
  image_size: 32
  train_path: None

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/LeNet_ImageNet/"
  save_checkpoint_freq: 2

model:
  name: "LeNet"
  in_channels: 3
  out_channels: 200

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.005  # Learning rate
  weight_decay: 0.001

#### training settings: learning rate scheme, loss, optimizer
train:

  num_epochs: 1000
  batch_size: 128
  train_size: 1

  loss: "CE"

logging:
  mode: online # disabled
  tags: [
      "ImageNet",
      "Classification",
      "LeNet",
      "Frequentist",
    ]
