#### general settings
name: MCDropout
train_type: mcd-linreg
eval_type: bnn
gpu_ids: [2]


#### datasets
data:
  name: "simulated"
  n: 10000

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/MCDropout_L1/"
  save_checkpoint_freq: 5


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.005  # Learning rate
  weight_decay: 0.001

#### training settings: learning rate scheme, loss, optimizer
train:
  model_name: "MLP"

  num_epochs: 100
  batch_size: 1024
  train_size: 1
  n_blocks: 1

  in_channels: 1
  out_channels: 1

  loss: "ELBO"
