#### general settings
name: R2D2
train_type: r2d2-linreg
eval_type: bnn
gpu_ids: [2]


#### datasets
data:
  name: "simulated"
  n: 10000
  scenario: 4

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/R2D2MLP_L3_S4/"
  save_checkpoint_freq: 5


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.005  # Learning rate
  weight_decay: 0.001

#### training settings: learning rate scheme, loss, optimizer
train:
  model_name: "R2D2MLP"

  num_epochs: 200
  batch_size: 1024
  train_size: 1
  n_blocks: 3

  beta: 0.0001

  r2d2_scale:
  prior_phi_prob: 0.6
  prior_psi_shape: 0.5
  beta_rho_scale: [-4, 0.05]
  bias_rho_scale: [-4, 0.05]
  weight_xi_shape: 0.3
  weight_omega_shape: 0.5

  in_channels: 200
  out_channels: 1

  loss: "ELBO"
