#### general settings
name: BPN
train_type: bnn-uncertainty
eval_type: bnn
gpu_ids: [2]


#### datasets
data:
  image_size: 32
  in: "CIFAR10"
  ood: "FashionMNIST"

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/R2D2LeNet_CIFAR_FashionMNIST_OOD/"
  save_checkpoint_freq: 2


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.001  # Learning rate
  weight_decay: 0.001

#### training settings: learning rate scheme, loss, optimizer
train:
  model_name: "R2D2LeNet"

  num_epochs: 100
  batch_size: 64
  train_size: 1

  n_samples: 10

  beta: 0.005

  r2d2_scale:
  prior_phi_prob: 0.6
  prior_psi_shape: 0.5
  beta_rho_scale: [-2.5, 0.05]
  bias_rho_scale: [-2.5, 0.05]
  weight_xi_shape: 0.3
  weight_omega_shape: 0.5

  in_channels: 3
  out_channels: 10

  loss: "ELBO"
